---
title: "mri-overview"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---
<div style="margin-bottom:100px;">
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
</div>

# Overview

Goal is to create an interactive flow chart for the steps required for MRI/fMRI analyses

This is a test run to see if we can get a plot up and running

Here is a helpful link for formatting: <https://bookdown.org/yihui/rmarkdown/html-document.html#document-dependencies>

<div style="margin-bottom:50px;">
</div>

```{r, echo=FALSE}
#Run library collapsible Tree
library("collapsibleTree")
# gsheet helps load in google data
library(gsheet)
# DT allows for interactive table
library(DT)

```


## fMRI preprocessing steps {.tabset .tabset-fade}
<div style="margin-bottom:50px;">
</div>
### Flow chart
```{r, echo=FALSE, results="hide"}



#Here we can organize the nodes


preprocessing <- data.frame(
  Manager = c(
    NA, "Ana", "Ana", "Bill", "Bill", "Bill", "Claudette", "Claudette", "Danny",
    "Fred", "Fred", "Grace", "Larry", "Larry", "Nicholas", "Nicholas"
  ),
  Employee = c(
    "Ana", "Bill", "Larry", "Claudette", "Danny", "Erika", "Fred", "Grace",
    "Henri", "Ida", "Joaquin", "Kate", "Mindy", "Nicholas", "Odette", "Peter"
  ),
  Title = c(
    "President", "VP Operations", "VP Finance", "Director", "Director", "Scientist",
    "Manager", "Manager", "Jr Scientist", "Operator", "Operator", "Associate",
    "Analyst", "Director", "Accountant", "Accountant"
  )
)


```

```{r, echo=FALSE}
collapsibleTree(preprocessing, c("Manager", "Employee"), collapsed = FALSE)
```

### Resources
<div style="margin-bottom:50px;">
</div>


## fMRI preprocessing steps {.tabset .tabset-fade}
<div style="margin-bottom:50px;">
</div>
### Flow chart
```{r, echo=FALSE, results="hide"}
#Here we can organize the nodes
org <- data.frame(
  Manager = c(
    NA, "Ana", "Ana", "Bill", "Bill", "Bill", "Claudette", "Claudette", "Danny",
    "Fred", "Fred", "Grace", "Larry", "Larry", "Nicholas", "Nicholas"
  ),
  Employee = c(
    "Ana", "Bill", "Larry", "Claudette", "Danny", "Erika", "Fred", "Grace",
    "Henri", "Ida", "Joaquin", "Kate", "Mindy", "Nicholas", "Odette", "Peter"
  ),
  Title = c(
    "President", "VP Operations", "VP Finance", "Director", "Director", "Scientist",
    "Manager", "Manager", "Jr Scientist", "Operator", "Operator", "Associate",
    "Analyst", "Director", "Accountant", "Accountant"
  )
)


```

```{r, echo=FALSE}
collapsibleTree(org, c("Manager", "Employee"), collapsed = FALSE)
```

### Resources
<div style="margin-bottom:50px;">
</div>


# Vocab

```{r, echo = FALSE}
#load in most recent vocab URL
url <- 'docs.google.com/spreadsheets/d/1U3Qi4Ns4POn9R8m0SEua6zU0cO5jjseMq3WrctPEtyo/edit?usp=slack&ts=5f24816f'
#make into sheet
vocab <- gsheet2tbl(url)
#display interactive plot
datatable(vocab)

```

